# Generated by Django 6.0.1 on 2026-01-09 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_alter_rental_user_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental_user',
            name='email',
        ),
    ]
