# Generated by Django 6.0.1 on 2026-01-12 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0007_vehicle_description_vehicle_owner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='name',
            new_name='vehicle_name',
        ),
    ]
