# Generated by Django 6.0.1 on 2026-01-12 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0008_rename_name_vehicle_vehicle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
