# Generated by Django 6.0.1 on 2026-01-16 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_latitude_vehicle_longitude_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
